export const GET_TRACKS_REQUEST = 'GET_TRACKS_REQUEST'
export const GET_TRACKS_SUCCESS = 'GET_TRACKS_SUCCESS'
export const GET_TRACKS_FAILURE = 'GET_TRACKS_FAILURE'
export const GET_TRACKS_ABORT = 'GET_TRACKS_ABORT'

export const SET_TRACK_INDEX = 'SET_TRACK_INDEX'

export const ADD_TRACKS_TO_QUEUE = 'ADD_TRACKS_TO_QUEUE'

export const GET_PLAYLISTS_REQUEST = 'GET_PLAYLISTS_REQUEST'
export const GET_PLAYLISTS_SUCCESS = 'GET_PLAYLISTS_SUCCESS'
export const GET_PLAYLISTS_FAILURE = 'GET_PLAYLISTS_FAILURE'
export const GET_PLAYLISTS_ABORT = 'GET_PLAYLISTS_ABORT'

export const NEXT_SONG = 'NEXT_SONG'
export const CLEAR_QUEUE = 'CLEAR_QUEUE'

export const UPDATE_API_ROOT = 'UPDATE_API_ROOT'

export const TOGGLE_QUEUE = 'TOGGLE_QUEUE'
