export const GET_TRACKS_REQUEST = 'GET_TRACKS_REQUEST'
export const GET_TRACKS_SUCCESS = 'GET_TRACKS_SUCCESS'
export const GET_TRACKS_FAILURE = 'GET_TRACKS_FAILURE'

export const SELECT_CURRENT_TRACK = 'SELECT_CURRENT_TRACK'
